export const VALID_HAIR_CODES = new Set(['', 'BLD', 'BLK', 'BLN', 'BLU', 'BRO', 'GRN', 'GRY', 'ONG', 'PLE', 'PNK', 'RED', 'SDY', 'WHI', 'XXX']);

export const VALID_EYE_CODES = new Set(['', 'BLU', 'BRO', 'GRN', 'GRY', 'HAZ', 'BLK', 'MAR', 'PNK', 'XXX']);

export const VALID_SKIN_CODES = new Set(['', 'BLK', 'DRK', 'DBR', 'FAR', 'LGT', 'LBR', 'MED', 'MBR', 'OLV', 'RUD', 'SAL', 'YEL', 'ALB']);

export const VALID_RACE_CODES = new Set(['A', 'B', 'I', 'U', 'W']);

export const VALID_SEX_CODES = new Set(['F', 'G', 'M', 'N', 'X', 'Y', 'Z']);

export const VALID_STATE_POB_CODES = new Set([
                'MD', 'DC', 'PA', 'DE', 'VA', 'WV', 'NY', 'NJ', 'NC', 'SC', 'OH', 'MA',
                'CT', 'GA', 'FL', 'AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'HI', 'ID', 'IL',
                'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MI', 'MN', 'MS', 'MO', 'MT', 'NB',
                'NV', 'NH', 'NM', 'ND', 'OK', 'OR', 'RI', 'SD', 'TN', 'TX', 'UT', 'VT',
                'WA', 'WI', 'WY'
            ]);

export const VALID_SCAR_MARK_CODES = new Set([
    "ART ARM", "ART BRSTS", "ART ELBOW", "ART HIP", "ART KNEE", "ART L ARM", "ART L BRST", "ART L EAR", "ART L EYE", "ART L FT",
    "ART L HND", "ART L LEG", "ART LARYNX", "ART R ARM", "ART R BRST", "ART R EAR", "ART R EYE", "ART R FT", "ART R HND",
    "ART R LEG", "ART SHLD", "BALD", "BLIND", "BLND EYE", "BLND L EYE", "BLND R EYE", "BRA LR ARM", "BRA LR LEG", "BRAC ARM",
    "BRAC L ARM", "BRAC L LEG", "BRAC LEG", "BRAC R ARM", "BRAC R LEG", "BRAC TEETH", "BRACE BACK", "BRACE NECK", "CANE",
    "CARD PACEM", "CATA L EYE", "CATA R EYE", "CATARACT", "CAUL L EAR", "CAUL R EAR", "CL LIP", "CLEFT CHIN", "CLEFT PAL",
    "COLOST APP", "CON LENSES", "CRIP L ARM", "CRIP L FGR", "CRIP L FT", "CRIP L HND", "CRIP L LEG", "CRIP L TOE",
    "CRIP R ARM", "CRIP R FGR", "CRIP R FT", "CRIP R HND", "CRIP R LEG", "CRIP R TOE", "CROSSEYED", "CRUTCHES",
    "DA ALCOHOL", "DA AMPHETA", "DA BARBITU", "DA COCAINE", "DA GLUE", "DA HALLUCI", "DA MARIJUA", "DA NARCOTI", "DA OTHER",
    "DA PAINT", "DA RITALIN", "DA ROHYPHL", "DEAF", "DEAF EAR", "DEAF L EAR", "DEAF MUTE", "DEAF R EAR", "DENT LOW", "DENT UP",
    "DENT UP LO", "DEV SEPTUM", "DIMP CHIN", "DIMP L CHK", "DIMP R CHK", "DISC ABDOM", "DISC ANKL", "DISC ARM", "DISC BACK",
    "DISC BRST", "DISC BUTTK", "DISC CHEEK", "DISC CHEST", "DISC CHIN", "DISC EAR", "DISC EYE", "DISC FACE", "DISC FGR",
    "DISC FHD", "DISC FOOT", "DISC HEAD", "DISC HIP", "DISC KNEE", "DISC L ANK", "DISC L ARM", "DISC L BRS", "DISC L BUT",
    "DISC L CHK", "DISC L EAR", "DISC L EYE", "DISC L FGR", "DISC L FT", "DISC L HIP", "DISC L HND", "DISC L LEG", "DISC L LIP",
    "DISC L WRS", "DISC LEG", "DISC LIP", "DISC LKNEE", "DISC LSHLD", "DISC LTHGH", "DISC NECK", "DISC NOSE", "DISC PENIS",
    "DISC R ANK", "DISC R ARM", "DISC R BRS", "DISC R BUT", "DISC R CHK", "DISC R EAR", "DISC R EYE", "DISC R FGR", "DISC R FT",
    "DISC R HIP", "DISC R HND", "DISC R LEG", "DISC R WRS", "DISC RKNEE", "DISC RSHLD", "DISC RTHGH", "DISC SHLD", "DISC THGH",
    "DISC U LIP", "DISC WRIST", "EAR TUBES", "EXTR BRST", "EXTR C NIP", "EXTR C VRT", "EXTR CBRST", "EXTR L FGR", "EXTR L NIP",
    "EXTR L TOE", "EXTR L VRT", "EXTR LBRST", "EXTR NIP", "EXTR R FGR", "EXTR R NIP", "EXTR R TOE", "EXTR RBRST", "EXTR VRT",
    "EXTRA LTTH", "EXTRA UTTH", "FRC ANKL", "FRC ARM", "FRC BACK", "FRC CLAVIC", "FRC FGR", "FRC FOOT", "FRC HAND", "FRC JAW",
    "FRC KNEE", "FRC L ANKL", "FRC L FGR", "FRC L FOOT", "FRC L HAND", "FRC L KNEE", "FRC L RIB", "FRC L SHLD", "FRC L TOE",
    "FRC L WRST", "FRC LCLAVI", "FRC LEG", "FRC LL ARM", "FRC LL JAW", "FRC LL LEG", "FRC LPELVI", "FRC LR ARM", "FRC LR JAW",
    "FRC LR LEG", "FRC NECK", "FRC NOSE", "FRC PELVIS", "FRC R ANKL", "FRC R FGR", "FRC R FOOT", "FRC R HAND", "FRC R KNEE",
    "FRC R RIB", "FRC R SHLD", "FRC R TOE", "FRC R WRST", "FRC RCLAVI", "FRC RIBS", "FRC RPELVI", "FRC SHLD", "FRC SKULL",
    "FRC SPINE", "FRC STERN", "FRC TOE", "FRC UL ARM", "FRC UL JAW", "FRC UL LEG", "FRC UR ARM", "FRC UR JAW", "FRC UR LEG",
    "FRC WRIST", "FRECKLES", "GLASSES", "GLAUCOMA", "GOLD TOOTH", "HAIR IMPL", "HARELIP", "HEAR AID", "HFR ANKL", "HFR ARM",
    "HFR BACK", "HFR CLAVIC", "HFR FGR", "HFR FOOT", "HFR HAND", "HFR JAW", "HFR KNEE", "HFR L ANKL", "HFR L FGR", "HFR L FOOT",
    "HFR L HAND", "HFR L KNEE", "HFR L RIB", "HFR L SHLD", "HFR L TOE", "HFR L WRST", "HFR LCLAVI", "HFR LEG", "HFR LL ARM",
    "HFR LL JAW", "HFR LL LEG", "HFR LPELVI", "HFR LR ARM", "HFR LR JAW", "HFR LR LEG", "HFR NECK", "HFR NOSE", "HFR PELVIS",
    "HFR R ANKL", "HFR R FGR", "HFR R FOOT", "HFR R HAND", "HFR R KNEE", "HFR R RIB", "HFR R SHLD", "HFR R TOE", "HFR R WRST",
    "HFR RCLAVI", "HFR RIBS", "HFR RPELVI", "HFR SHLD", "HFR SKULL", "HFR SPINE", "HFR STERN", "HFR TOE", "HFR UL ARM",
    "HFR UL JAW", "HFR UL LEG", "HFR UR ARM", "HFR UR JAW", "HFR UR LEG", "HFR WRIST", "HUMPBACKED", "IMPL PENIS", "INTRA ROD",
    "IUD", "MC ACNE", "MC ADD", "MC AIDS", "MC ALCOHOL", "MC ALLERGY", "MC ALZHMRS", "MC ARTHRTS", "MC BEHAVIO", "MC BLOOD",
    "MC CANCER", "MC DIABTIC", "MC DOWNSYN", "MC DRUGAB", "MC EATDIS", "MC HEART", "MC HIVPOS", "MC KIDNEY", "MC LIVER",
    "MC NERVOUS", "MC NRLGCAL", "MC OTHER", "MC PARPLGC", "MC PASTPRE", "MC PLMNARY", "MC PREGNAN", "MC QUADPLG", "MC SKIN",
    "MC TB", "MC THYROID", "MC TOURETE", "MIS PROST", "MISS ADND", "MISS APPNX", "MISS BRSTS", "MISS C VRT", "MISS GALL",
    "MISS INTES", "MISS L ARM", "MISS L EAR", "MISS L EYE", "MISS L FGR", "MISS L FJT", "MISS L FT", "MISS L HND", "MISS L KID",
    "MISS L LEG", "MISS L TES", "MISS L TOE", "MISS L VRT", "MISS LBRST", "MISS LLARM", "MISS LLLEG", "MISS LLUNG",
    "MISS LOVAR", "MISS LRARM", "MISS LRLEG", "MISS LRYNX", "MISS NOSE", "MISS OVARS", "MISS PANCR", "MISS PENIS",
    "MISS R ARM", "MISS R EAR", "MISS R EYE", "MISS R FGR", "MISS R FJT", "MISS R FT", "MISS R HND", "MISS R KID",
    "MISS R LEG", "MISS R TES", "MISS R TOE", "MISS RBRST", "MISS RLUNG", "MISS ROVAR", "MISS SPLEN", "MISS STOMA",
    "MISS THYRD", "MISS TONG", "MISS TONSL", "MISS UTRUS", "MISS VRT", "MOLE ABDOM", "MOLE ANKL", "MOLE BACK", "MOLE BRST",
    "MOLE BUTTK", "MOLE CHEST", "MOLE CHIN", "MOLE CHK", "MOLE EAR", "MOLE FGR", "MOLE FHD", "MOLE FOOT", "MOLE GROIN",
    "MOLE HAND", "MOLE HEAD", "MOLE HIP", "MOLE KNEE", "MOLE L ANK", "MOLE L ARM", "MOLE L BUT", "MOLE L CHK", "MOLE L EAR",
    "MOLE L EYE", "MOLE L FGR", "MOLE L FT", "MOLE L HIP", "MOLE L HND", "MOLE L KNE", "MOLE L LEG", "MOLE L LIP", "MOLE L SHD",
    "MOLE L THG", "MOLE L WRS", "MOLE LBRST", "MOLE LEG", "MOLE LIP", "MOLE NECK", "MOLE NOSE", "MOLE PENIS", "MOLE R ANK",
    "MOLE R ARM", "MOLE R BUT", "MOLE R CHK", "MOLE R EAR", "MOLE R EYE", "MOLE R FGR", "MOLE R FT", "MOLE R HIP", "MOLE R HND",
    "MOLE R KNE", "MOLE R LEG", "MOLE R SHD", "MOLE R THG", "MOLE R WRS", "MOLE RBRST", "MOLE SHLD", "MOLE THGH", "MOLE U LIP",
    "MUTE", "NM L ARM", "NM L BUTTK", "NM L FGR", "NM L FOOT", "NM L HND", "NM L LEG", "NM L THIGH", "NM L WRIST", "NM R ARM",
    "NM R BUTTK", "NM R FGR", "NM R FOOT", "NM R HND", "NM R LEG", "NM R THIGH", "NM R WRIST", "ORTH NAIL", "ORTH PLATE",
    "ORTH SCREW", "POCKMARKS", "PRCD ABDMN", "PRCD BACK", "PRCD EAR", "PRCD EARS", "PRCD EYE", "PRCD GNTLS", "PRCD L EAR",
    "PRCD L EYE", "PRCD L NIP", "PRCD LIP", "PRCD LLIP", "PRCD NIPPL", "PRCD NOSE", "PRCD R EAR", "PRCD R EYE", "PRCD R NIP",
    "PRCD TONGU", "PROT L JAW", "PROT U JAW", "RTAT ABDM", "RTAT ANKL", "RTAT ARM", "RTAT BACK", "RTAT BRST", "RTAT BUTTK",
    "RTAT CALF", "RTAT CHEEK", "RTAT CHEST", "RTAT CHIN", "RTAT EAR", "RTAT ELBOW", "RTAT FACE", "RTAT FARM", "RTAT FHD",
    "RTAT FLBOD", "RTAT FNGR", "RTAT FOOT", "RTAT GROIN", "RTAT HAND", "RTAT HIP", "RTAT KNEE", "RTAT L ARM", "RTAT L CHK",
    "RTAT L EAR", "RTAT L ELB", "RTAT L FGR", "RTAT L HIP", "RTAT L HND", "RTAT L LEG", "RTAT L WRS", "RTAT LANKL",
    "RTAT LBRST", "RTAT LBUTK", "RTAT LCALF", "RTAT LEG", "RTAT LFARM", "RTAT LFOOT", "RTAT LIP", "RTAT LKNEE", "RTAT LSHLD",
    "RTAT LTHGH", "RTAT LWLIP", "RTAT NECK", "RTAT NOSE", "RTAT PENIS", "RTAT R ARM", "RTAT R CHK", "RTAT R EAR", "RTAT R ELB",
    "RTAT R FGR", "RTAT R HIP", "RTAT R HND", "RTAT R LEG", "RTAT R WRS", "RTAT RANKL", "RTAT RBRST", "RTAT RBUTK",
    "RTAT RCALF", "RTAT RFARM", "RTAT RFOOT", "RTAT RHEAD", "RTAT RKNEE", "RTAT RSHLD", "RTAT RTHGH", "RTAT SHLD",
    "RTAT THGH", "RTAT ULARM", "RTAT UPLIP", "RTAT URARM", "RTAT WRS", "SC ABDOM", "SC ANKL", "SC ARM", "SC BACK",
    "SC BREAST", "SC BUTTK", "SC CALF", "SC CHEST", "SC CHIN", "SC CHK", "SC EAR", "SC ELBOW", "SC EYE", "SC F ARM", "SC FACE",
    "SC FGR", "SC FHD", "SC FOOT", "SC GROIN", "SC HAND", "SC HEAD", "SC HIP", "SC KNEE", "SC L ANKL", "SC L ARM",
    "SC L BRST", "SC L BUTTK", "SC L CALF", "SC L CHK", "SC L EAR", "SC L ELB", "SC L EYE", "SC L FGR", "SC L FT", "SC L HIP",
    "SC L HND", "SC L KNEE", "SC L LEG", "SC L SHLD", "SC L THGH", "SC L WRIST", "SC LEG", "SC LF ARM", "SC LIP",
    "SC LOW LIP", "SC NECK", "SC NOSE", "SC PENIS", "SC R ANKL", "SC R ARM", "SC R BRST", "SC R BUTTK", "SC R CALF",
    "SC R CHK", "SC R EAR", "SC R ELB", "SC R EYE", "SC R FGR", "SC R FT", "SC R HIP", "SC R HND", "SC R KNEE", "SC R LEG",
    "SC R SHLD", "SC R THGH", "SC R WRIST", "SC RF ARM", "SC SHLD", "SC THGH", "SC UL ARM", "SC UP LIP", "SC UR ARM",
    "SC WRIST", "SHRT L LEG", "SHRT R LEG", "SHUNT ART", "SHUNT CERB", "SKL PLATE", "SLVR TOOTH", "STAPLES", "STUTTERS",
    "TAT ABDOM", "TAT ANKL", "TAT ARM", "TAT BACK", "TAT BREAST", "TAT BUTTK", "TAT CALF", "TAT CHEEK", "TAT CHEST",
    "TAT CHIN", "TAT EAR", "TAT ELBOW", "TAT FACE", "TAT FARM", "TAT FHD", "TAT FLBODY", "TAT FNGR", "TAT FOOT", "TAT GROIN",
    "TAT HAND", "TAT HEAD", "TAT HIP", "TAT KNEE", "TAT L ANKL", "TAT L ARM", "TAT L BRST", "TAT L BUTK", "TAT L CALF",
    "TAT L CHK", "TAT L EAR", "TAT L FGR", "TAT L FOOT", "TAT L HIP", "TAT L HND", "TAT L KNEE", "TAT L LEG", "TAT L SHLD",
    "TAT L THGH", "TAT L WRS", "TAT LEG", "TAT LELBOW", "TAT LF ARM", "TAT LIP", "TAT LW LIP", "TAT NECK", "TAT NOSE",
    "TAT PENIS", "TAT R ANKL", "TAT R ARM", "TAT R BRST", "TAT R BUTK", "TAT R CALF", "TAT R CHK", "TAT R EAR", "TAT R FGR",
    "TAT R FOOT", "TAT R HIP", "TAT R HND", "TAT R KNEE", "TAT R LEG", "TAT R SHLD", "TAT R THGH", "TAT R WRS", "TAT RELBOW",
    "TAT RF ARM", "TAT SHLD", "TAT THGH", "TAT UL ARM", "TAT UP LIP", "TAT UR ARM", "TAT WRS", "TD ACONVUL", "TD ADEPRES",
    "TD ANALGES", "TD ANTBTCS", "TD ANTINFL", "TD BRNCHDL", "TD CARDIAC", "TD HYPNOTI", "TD INSULIN", "TD OTHER", "TD RITALIN",
    "TD TRANQUI", "TRANSSXL", "TRANSVST", "TUBE L EAR", "TUBE R EAR", "VASC PROTH", "WHEELCHAIR", "WIRE SUTUR"
]);

export const VALID_MISC_NUM_PREFIXES = new Set([
    "AF-", "AR-", "AS-", "CG-", "MC-", "MD-", "MDA", "MDB", "MDC", "MDD", "MDE", "MDF",
    "MDG", "MDH", "MDI", "MDJ", "MDK", "MDL", "MDM", "MDN", "MDO", "MDP", "MDQ", "MDR",
    "MDS", "MDT", "MDU", "MDV", "MDW", "MDX", "MDY", "MDZ", "MP-", "NS-", "OA-", "PP-",
    "PS-", "SS-", "VA-"
]);

export const VALID_STREET_DIR_CODES = new Set(['N', 'S', 'E', 'W', 'NE', 'NW', 'SE', 'SW']);

export const VALID_STREET_SUF_CODES = new Set(['ST', 'RD', 'DR', 'AV', 'AVE', 'BL', 'BV', 'BLVD', 'CI', 'CIR', 'CO', 'CT', 'CV', 'CR', 'CS', 'EX', 'FWY', 'GT', 'HW', 'HY', 'HTS', 'LA', 'LN', 'LP', 'PK', 'PL', 'PY', 'PZ', 'SQ', 'TER', 'TP', 'TR', 'TRL', 'UN', 'WY']);